# Generated by Django 5.2.4 on 2025-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="uploaded_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
